-- Equivalent of the original Alembic migrations
-- (20260717_01 initial_schema + 20260717_02 add_click_analytics_fields),
-- combined into the final desired schema. Run this ONCE against a fresh
-- database. If you are pointing this backend at an existing database that
-- Alembic already migrated, you do NOT need to run this file — the schema
-- is unchanged and Sequelize connects to it as-is.

CREATE TABLE IF NOT EXISTS domains (
    id SERIAL PRIMARY KEY,
    hostname VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_domains_hostname UNIQUE (hostname)
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_domains_hostname ON domains (hostname);

CREATE TABLE IF NOT EXISTS links (
    id UUID PRIMARY KEY, -- generated by the application (Sequelize UUIDV4), matching the original SQLAlchemy default=uuid4
    domain_id INTEGER NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
    slug VARCHAR(80) NOT NULL,
    asin VARCHAR(10) NOT NULL,
    target_country VARCHAR(2) NOT NULL,
    keywords JSONB NOT NULL,
    associate_tag VARCHAR(100),
    click_sequence BIGINT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_links_domain_slug UNIQUE (domain_id, slug),
    CONSTRAINT ck_links_asin_format CHECK (asin ~ '^[A-Z0-9]{10}$'),
    CONSTRAINT ck_links_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT ck_links_click_sequence_nonnegative CHECK (click_sequence >= 0),
    CONSTRAINT ck_links_keywords_array_length CHECK (
        jsonb_typeof(keywords) = 'array' AND jsonb_array_length(keywords) BETWEEN 1 AND 20
    ),
    CONSTRAINT ck_links_target_country CHECK (
        target_country IN ('IN','US','UK','CA','AU','DE','FR','IT','ES','JP','AE','SA','SG','BR','MX')
    )
);
CREATE INDEX IF NOT EXISTS ix_links_asin ON links (asin);
CREATE INDEX IF NOT EXISTS ix_links_domain_id ON links (domain_id);

CREATE TABLE IF NOT EXISTS click_events (
    id BIGSERIAL PRIMARY KEY,
    link_id UUID NOT NULL REFERENCES links(id) ON DELETE CASCADE,
    clicked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    keyword_used VARCHAR(100),
    keyword_position INTEGER NOT NULL CHECK (keyword_position >= 0),
    request_method VARCHAR(10) NOT NULL,
    user_agent TEXT,
    referrer TEXT,
    ip_hash VARCHAR(64),
    classification VARCHAR(20) NOT NULL DEFAULT 'unknown',
    device_category VARCHAR(20) NOT NULL DEFAULT 'unknown',
    operating_system VARCHAR(50) NOT NULL DEFAULT 'unknown',
    browser VARCHAR(80) NOT NULL DEFAULT 'unknown',
    device_family VARCHAR(100) NOT NULL DEFAULT 'unknown',
    country VARCHAR(10),
    city VARCHAR(255),
    language VARCHAR(35) NOT NULL DEFAULT 'unknown',
    referrer_domain VARCHAR(255) NOT NULL DEFAULT 'direct',
    visitor_hash VARCHAR(64),
    is_bot BOOLEAN NOT NULL DEFAULT false,
    is_preview BOOLEAN NOT NULL DEFAULT false,
    is_prefetch BOOLEAN NOT NULL DEFAULT false,
    is_human BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS ix_click_events_clicked_at ON click_events (clicked_at);
CREATE INDEX IF NOT EXISTS ix_click_events_link_id ON click_events (link_id);
CREATE INDEX IF NOT EXISTS ix_click_events_link_clicked_at ON click_events (link_id, clicked_at);
CREATE INDEX IF NOT EXISTS ix_click_events_link_human ON click_events (link_id, is_human);
CREATE INDEX IF NOT EXISTS ix_click_events_link_classification ON click_events (link_id, classification);
CREATE INDEX IF NOT EXISTS ix_click_events_device_category ON click_events (device_category);
CREATE INDEX IF NOT EXISTS ix_click_events_operating_system ON click_events (operating_system);
CREATE INDEX IF NOT EXISTS ix_click_events_browser ON click_events (browser);
CREATE INDEX IF NOT EXISTS ix_click_events_keyword_used ON click_events (keyword_used);
CREATE INDEX IF NOT EXISTS ix_click_events_referrer_domain ON click_events (referrer_domain);
CREATE INDEX IF NOT EXISTS ix_click_events_visitor_hash ON click_events (visitor_hash);
